FROM continuumio/miniconda3 

RUN conda install python=3.12.2 \
    && conda install statsmodels==0.14.1 \
    && conda install seaborn==0.13.2 \
    && conda install pandas=2.2.0 \
    && conda install numpy=1.26.4 \
    && conda install altair=5.2.0 \
    && conda install imbalanced-learn=0.12.0 \
    && conda install matplotlib=3.8.3 \
    && conda install scikit-learn=1.4.1.post1
