name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair == 4.1.0
  - altair_saver == 0.5.0
  - altair_viewer
  - vega_datasets
  - imbalanced-learn == 0.8.1
  - matplotlib == 3.5.1
  - numpy == 1.21.5
  - pandas == 1.4.1
  - scikit-learn == 1.0.2
  - seaborn == 0.11.2
  - statsmodels == 0.13.1
  - python=3.9.10
  - tabulate == 0.8.9
  - click
  - requests
  - selenium
  - pillow
  - ipython == 8.0.1