name: group_13_environment
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - python==3.11 
  - statsmodels==0.14.1 
  - seaborn==0.13.2 
  - pandas=2.2.0 
  - numpy=1.26.4 
  - altair=5.2.0 
  - imbalanced-learn=0.12.0 
  - matplotlib=3.8.3 
  - scikit-learn=1.4.1.post1 
  - statsmodels==0.14.1 
  - tabulate==0.9.0 
  - click==8.1.7 
  - pillow==10.2.0 
  - ipython==8.20.0 
  - make==4.2.1 
  - vl-convert-python==1.3.0 
  - pytest==8.1.1 
  - pip:
    - lapttoppred==0.1.0

    