name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - imbalanced-learn
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - statsmodels
  - python=3.12.2
  - click
  - request
