name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair == 5.2.0
  - imbalanced-learn == 0.12.0
  - matplotlib == 3.8.3
  - numpy == 1.26.4
  - pandas == 2.2.1
  - scikit-learn == 1.4.1.post1
  - seaborn == 0.13.2
  - statsmodels == 0.14.1
  - python=3.12.2
  - tabulate == 0.9.0
  - click
  - request
  - selenium
  - vl-convert-python
