name: project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.2.0
  - imbalanced-learn
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - statsmodels
  - python=3.12.2
  - click
  - request
  - selenium
  - altair_saver=0.5.0
  - altair_viewer=0.4.0 
